
drop type if exists grocery;
create type grocery as ENUM (
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

Create table if not exists shopping_list (
    id integer primary key generated by default as identity,
    name text not null,
    price  decimal(12, 2) not null,
    date_added timestamp default now() not null,
    checked BOOLEAN default false,
    category grocery not null
);